#!/usr/bin/env python3
import os
import sys
import deromanize
import yaml

PROJECT_DIR = os.path.dirname(os.path.dirname(deromanize.__file__))
CONFIG_FILE = os.path.join(PROJECT_DIR, 'data', 'old.yml')
CUTOFF = 5
PROFILE = yaml.safe_load(open(CONFIG_FILE))

# define the key
key = deromanize.KeyGenerator(PROFILE)

@key.processor
def decode(key, word):
    # add aleph to words that begin with vowels.
    if word[0] in PROFILE['vowels']:
        word = 'ʾ' + word
    # remove doubled letters
    newword = ''
    for i, c in enumerate(word):
        if i == 0 or c != word[i-1]:
            newword += c
    # get ending clusters, then beginning clusters, then whatever's left in the
    # middle.
    end, remaider = key['end'].getpart(newword)
    front, remaider = key['front'].getpart(remaider)
    middle = key['base'].getallparts(remaider).add()
    hebword = front + middle + end
    hebword.sort()
    return hebword


def main():
    for word in sys.argv[1].lower().split():
        hebword = decode(word)
        print(word + ':  ', '\u200E, '.join(str(i) for i in hebword[:CUTOFF]))

if __name__ == '__main__':
    main()
